### ISSUE TITLE
正在输入中文的时候按回车不应该触发Enter的相关事件

### ISSUE THREAD

**Issue by meng-fanlei** [lakejs/lake#9]
比如正在输入nihao的时候，没有选词，而是直接按下Enter，预期的结果应该是nihao上屏，并且不会新增段落。
我能想到的一个方法是在触发Enter的keydown事件后，检测event.isComposing是否为true，如果为true则直接return。
在macOS及windows11均稳定复现该bug。

**Comment by luolonghao** [comment]
我在改进这块代码，需要考虑 composing 状态。

**Comment by luolonghao** [comment]
最新版本已修复。

**Comment by luolonghao** [comment]
原来的处理方式只解决了 Windows 系统，MacOS 需要另外加判断。 https://github.com/lakejs/lake/commit/f96aa4763078e448fc7fd15fdf57a50ec44277b4
